-- MySQL Script generated by MySQL Workbench
-- Thu Nov 28 19:21:46 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gestionturnos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gestionturnos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gestionturnos` DEFAULT CHARACTER SET utf8mb4 ;
USE `gestionturnos` ;

-- -----------------------------------------------------
-- Table `gestionturnos`.`administradorservicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestionturnos`.`administradorservicio` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  `Apellido` VARCHAR(50) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Contraseña` VARCHAR(255) NOT NULL,
  `PermisosEspeciales` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `Email` (`Email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gestionturnos`.`trabajadorsanitario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestionturnos`.`trabajadorsanitario` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  `Apellido` VARCHAR(50) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Contraseña` VARCHAR(255) NOT NULL,
  `Teléfono` VARCHAR(15) NULL DEFAULT NULL,
  `CentroTrabajo` VARCHAR(100) NULL DEFAULT NULL,
  `Puesto` ENUM('Médico', 'Enfermero', 'TCAE') NOT NULL,
  `Localidad` VARCHAR(100) NULL DEFAULT NULL,
  `PreferenciasHorarias` TEXT NULL DEFAULT NULL,
  `DisponibilidadHorasExtras` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `Email` (`Email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gestionturnos`.`jornada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestionturnos`.`jornada` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NOT NULL,
  `HoraInicio` TIME NOT NULL,
  `HoraFin` TIME NOT NULL,
  `Estado` ENUM('Disponible', 'Ocupada') NOT NULL,
  `TrabajadorID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `TrabajadorID` (`TrabajadorID` ASC) VISIBLE,
  CONSTRAINT `jornada_ibfk_1`
    FOREIGN KEY (`TrabajadorID`)
    REFERENCES `gestionturnos`.`trabajadorsanitario` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gestionturnos`.`cambioturno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestionturnos`.`cambioturno` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `TrabajadorSolicitanteID` INT(11) NOT NULL,
  `TrabajadorAceptanteID` INT(11) NULL DEFAULT NULL,
  `JornadaID` INT(11) NOT NULL,
  `FechaSolicitud` DATE NOT NULL,
  `EstadoCambio` ENUM('Pendiente', 'Aceptado', 'Rechazado') NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `TrabajadorSolicitanteID` (`TrabajadorSolicitanteID` ASC) VISIBLE,
  INDEX `TrabajadorAceptanteID` (`TrabajadorAceptanteID` ASC) VISIBLE,
  INDEX `JornadaID` (`JornadaID` ASC) VISIBLE,
  CONSTRAINT `cambioturno_ibfk_1`
    FOREIGN KEY (`TrabajadorSolicitanteID`)
    REFERENCES `gestionturnos`.`trabajadorsanitario` (`ID`),
  CONSTRAINT `cambioturno_ibfk_2`
    FOREIGN KEY (`TrabajadorAceptanteID`)
    REFERENCES `gestionturnos`.`trabajadorsanitario` (`ID`),
  CONSTRAINT `cambioturno_ibfk_3`
    FOREIGN KEY (`JornadaID`)
    REFERENCES `gestionturnos`.`jornada` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gestionturnos`.`vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestionturnos`.`vehiculo` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Modelo` VARCHAR(50) NOT NULL,
  `PlazasDisponibles` TINYINT(4) NOT NULL,
  `PropietarioID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `PropietarioID` (`PropietarioID` ASC) VISIBLE,
  CONSTRAINT `vehiculo_ibfk_1`
    FOREIGN KEY (`PropietarioID`)
    REFERENCES `gestionturnos`.`trabajadorsanitario` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gestionturnos`.`viaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestionturnos`.`viaje` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NOT NULL,
  `Hora` TIME NOT NULL,
  `Origen` VARCHAR(100) NOT NULL,
  `Destino` VARCHAR(100) NOT NULL,
  `VehiculoID` INT(11) NOT NULL,
  `PlazasOcupadas` TINYINT(4) NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  INDEX `VehiculoID` (`VehiculoID` ASC) VISIBLE,
  CONSTRAINT `viaje_ibfk_1`
    FOREIGN KEY (`VehiculoID`)
    REFERENCES `gestionturnos`.`vehiculo` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
